### ISSUE TITLE
Question: withGoodbye HOC purpose...

### ISSUE THREAD

**Issue by mdwagner** [xJkit/react-goodbye#8]
Nice library! However, I was trying to undestand how your withGoodbye HOC works and I'm a little confused...
First off, you export a Provider, a Consumer, and a HOC. Nothing out of the usual there. But after looking at the HOC, it's using the Provider from the Context to wrap the component? Why wouldn't you use the Consumer? The only thing I could gather from this approach, is that you can call the HOC at the root instead of wrapping the Provider manually. But IMO that goes against the convention of a HOC, which is supposed to add prop(s) to a Component and move on. Can you explain what your reasoning was for this approach? Also, on a different note, I would suggest creating Context with a default state. This makes it easier to test and if someone ever uses this library without wrapping it with the Provider.

Thank you for your time!

**Comment by xJkit** [comment]
Hi, @mdwagner, good questions. Nice to have discussion with you.

`withGoodBye` is indeed a HoC but for react router provider like `BrowserRouter`, and it injects the handle function into the router provider to gain control of the routing transition.  With those logics encapsulated inside the `Provider` component, it can send more declarative APIs to the users that works together with their UI components via **consumer**, including **handleOk**, **handleCancel** and **isShow** state. The default exported component `GoodBye` is the **consumer**.

1. Is the `withGoodBye` a normal HoC? Yes! `withGoodBye` is just the props proxy that injects the handle function. You can still pass other props into the base component after decorating them.
2. Why do I need to use `Provider` to wrap the base component, not consumer? Because `Provider` needs to be on top of the tree so that the consumer can gain control of the routing transition by React context with declarative APIs.
3. Why don't I set the initial state when creating context? It's personal preferences. IMO, because the initial states include handle functions, I think it's much simpler to set all of them in the Provider component.

Welcome to provider a cleaner solution 👍

**Comment by xJkit** [comment]
Hi @mdwagner , thank you for your reviews. Having discussion is great! I think I can answer your questions 
1. AFAIK, the `HoC` pattern takes a base component and return a new one. What I do is to inject the `getUserConfirmation` function into the Router Provider as a prop, get the callback function back to my Provider component and finally return a new provider component. 
2. I use my **Provider** as data source to communicate with my **Consumer**.

**Comment by mdwagner** [comment]
Oh ok, I'm starting to get what you did now. I did however notice that your value prop (on your Provider) is being passed an object literal, instead of a bound object literal. This is listed as a gotcha on React's documentation because it can cause unintentional re-renders.
[Here's the code that's doing it](https://github.com/xJkit/react-goodbye/blob/master/src/GoodByeProvider.js#L40)
[Here's React's documentation on it](https://reactjs.org/docs/context.html#caveats)

**Comment by xJkit** [comment]
@mdwagner  You are right! I will fix this ,thanks!!

**Comment by xJkit** [comment]
I enhance this cases, please check #9.

Any other discussions are welcome. 💯
